# E_AI 03 - Neural Network


> 학번:
>
> 이름:

---

In [ ]:
import numpy as np
import matplotlib.pylab as plt

In [2]:
# 3.1

def step_function(x):
    if x > 0:
        return 1
    else:
        return 0

In [3]:
# 3.2

def step_function(x):
    y = x > 0
    return y.astype( np.int )

In [4]:
# 3.3

import numpy as np
x = np.array([-1.0, 1.0, 2.0])

print(x)
# array([-1., 1., 2.])

y = x > 0
print(y)
# array([False, True, True], dtype=bool)

array([False,  True,  True])

In [5]:
# 3.4

y = y.astype(np.int)
y
# array([0, 1, 1])

array([0, 1, 1])

In [ ]:
# 3.5

import numpy as np
import matplotlib.pylab as plt

def step_function(x):
    return np.array(x > 0, dtype=np.int)

X = np.arange(-5.0, 5.0, 0.1)
Y = step_function(X)
plt.plot(X, Y)
plt.ylim(-0.1, 1.1)
plt.show()



In [7]:
# 3.6

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [ ]:
# 3.7

x = np.array([-1.0, 1.0, 2.0])
sigmoid(x)

In [ ]:
# 3.8

x = np.arange(-5.0, 5.0, 0.1)
y = sigmoid(x)

plt.plot(x, y)
plt.ylim(-0.1, 1.1)
plt.show()

In [ ]:
# 3.9

def relu(x):
    return np.maximum(0, x)

In [ ]:
# 3.10

import numpy as np

A = np.array([1, 2, 3, 4])
print(A)
# [1 2 3 4]

print(np.ndim(A))
# 1

print(A.shape)
# (4,)

print(A.shape[0])
# 4


In [ ]:
# 3.11

B = np.array([[1,2], [3,4], [5,6]])
print(B)
# [[1 2]
#  [3 4]
#  [5 6]]

print(np.ndim(B))
# 2

print(B.shape)
# (3, 2)

In [ ]:
# 3.12

A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

print( np.dot(A, B) )
# [[19 22]
#  [43 50]]


In [ ]:
# 3.13

A = np.array([[1,2,3], [4,5,6]])
B = np.array([[1,2], [3,4], [5,6]])

print( np.dot(A, B) )
# [[22 28]
#  [49 64]]


In [ ]:
# 3.14

X = np.array([1, 2])
print(X.shape)
# (2,)

W = np.array([[1, 3, 5], [2, 4, 6]])
print(W.shape)
# (2, 3)

Y = np.dot( X, W )
print(Y)
# [ 5 11 17]

In [ ]:
# 3.15 +

X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])


In [ ]:
# 3.16

Z1 = sigmoid(A1)

print(A1)
print(Z1)

In [ ]:
# 3.17 +

W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

print(Z1.shape)
print(W2.shape)
print(B2.shape)



In [ ]:
# 3.18

def identity_function(x):
  return x

W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3)

In [ ]:
# 3.19 +

def init_network():
  network = {}
  network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
  network['b1'] = np.array([0.1, 0.2, 0.3])
  network['W2'] = np.array([[0.1, 0.4], [0.2, 0.4], [0.3, 0.6]])
  network['b2'] = np.array([0.1, 0.2])
  network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
  network['b3'] = np.array([0.1, 0.2])
  
  return network


def forward( network, x ):
  W1, W2, W3 = network['W1'], network['W2'], network['W3']
  b1, b2, b3 = network['b1'], network['b2'], network['b3']
  


In [ ]:
# 3.20

a = np.array([0.3, 2.9, 4.0])

exp_a = np.exp(a)
print(exp_a)

sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

y = exp_a / sum_exp_a
print(y)

In [ ]:
# 3.21

def softmax(a):
  exp_a = np.exp(a)
  sum_exp_a = np.sum(exp_a)
  y = exp_a / sum_exp_a
  
  return y

In [ ]:
# 3.22

a = np.array([1010, 1000, 990])
np.exp(a) / np.sum( np.exp(a) )

In [ ]:
# 3.23

c = np.max(a)
a - c

In [ ]:
# 3.24

np.exp(a - c) / np.sum( np.exp(a - c) )

In [ ]:
# 3.25

def softmax(a):
  c = np.max(a)
  exp_a = np.exp(a - c)
  sum_exp_a = np.sum(exp_a)
  y = exp_a / sum_exp_a
  
  return y

In [ ]:
# 3.26

a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
print(y)

print(np.sum(y))

In [ ]:
# 3.29

from sklearn.datasets import fetch_openml
X, y = fetch_openml('mnist_784', version=1, return_X_y=True)

X = X.astype(np.uint8)
y = y.astype(np.uint8)

x_train = X[:60000]
x_test = X[60000:]
t_train = y[:60000]
t_test = y[60000:]

print(x_train.shape)
print(t_train.shape)
print(x_test.shape)
print(t_test.shape)


In [ ]:
# 3.30

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

img = x_train[0]
label = t_train[0]
print(label)

print(img.shape)
img = img.reshape(28, 28)
print(img.shape)

plt.imshow(img, cmap='gray')
plt.show()

In [ ]:
# 3.31 *

img_count = 3*5

fig = plt.figure()
indices = np.random.choice( x_train.shape[0], img_count ) 

imgs = x_train[ indices ]
labels = t_train[ indices ]

for i in range(img_count):
    ax = fig.add_subplot(3, 5, i+1)
    ax.set_title( labels[i] )
    ax.set_xticks([])
    ax.set_yticks([])
    ax.imshow(imgs[i].reshape(28,28))

plt.show()

In [ ]:
# 3.32

!wget -O sample_weights.pkl https://bit.ly/2nsrh3M

In [ ]:
# 3.33
import pickle

def get_data():
    (x_train, t_train), (x_test, t_test) = \
        load_mnist(flatten=True, normalize=True, one_hot_label=False)
    return x_test, t_test

def init_network():
    with open('sample_weights.pkl', 'rb') as f:
        network = pickle.load(f)
        
    return network

def predict(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
        
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = softmax(a3)
    
    return y


In [ ]:
# 3.34


In [ ]:
# 3.35


In [ ]:
# 3.36


In [ ]:
# 3.37

print( list( range(0, 10) ) )
print( list( range(0, 10, 3) ) )

In [ ]:
# 3.38

x = np.array([[0.1, 0.8, 0.1], 
              [0.3, 0.1, 0.6],
              [0.2, 0.5, 0.3],
              [0.8, 0.1, 0.1]])

print( np.argmax(x, axis=1) )
print( np.argmax(x, axis=0) )


In [ ]:
# 3.39

y = np.array([1, 2, 1, 0])
t = np.array([1, 2, 0, 0])

print( y == t )
print( np.sum(y == t) )